KafkaServer {
   org.apache.kafka.common.security.plain.PlainLoginModule required
   username="admin"
   password="admin-password"
   user_CtelRnDDefaultUser="CtelRnDDefaultUserPassword"
   user_yunomix2834="dinhanst2832004"
   user_admin="admin-password";
};
